### ISSUE TITLE
HA supervised working dir changed in 0.107 beta

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/docker#100]
## The problem

After 0.107.0b0 command_line integrations without the full path to a script don't work anymore.

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): 0.106.6
- Operating environment (Hass.io/Docker/Windows/etc.): HA supervised on ubuntu
- Integration causing this issue: command_line integrations
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/sensor.command_line/

## Problem-relevant `configuration.yaml`

Fails
```yaml
sensor
  - platform: command_line
    name: "RLC MQTT Test Switch"
    command: "python3 scripts/real_last_change.py switch.mqtt_test"
    scan_interval: 60
```
Works
```yaml
sensor
  - platform: command_line
    name: "RLC MQTT Test Switch"
    command: "python3 /config/scripts/real_last_change.py switch.mqtt_test"
    scan_interval: 60
```
A sensor with 'pwd' command
```yaml
  - platform: command_line
    name: "HA Path"
    command: "pwd"
```
shows that HA runs in: `/run/s6/services/home-assistant`

## Traceback/Error logs

```txt
python3: can't open file 'scripts/real_last_change.py': [Errno 2] No such file or directory
2020-03-12 22:39:47 ERROR (SyncWorker_0) [homeassistant.components.command_line.sensor] Command failed: python3 scripts/real_last_change.py switch.mqtt_test
```

## Additional information
I would not consider this as a bug, but I think it should be mentioned in the release notes.
