### ISSUE TITLE
Unable to start homeassistant/raspberrypi2-homeassistant:0.107.1: permission denied on /var/run/s6

### ISSUE THREAD

**Issue by GMTA** [home-assistant/docker#104]
The `homeassistant/raspberrypi2-homeassistant:0.107.1` image refuses to start with the following error message:

```
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

This is on a clean container with only `/config` mounted (from a previous 0.106.6 installation).

I'm running the image through `docker-compose` with the following service definition:

```
  homeassistant:
    image: homeassistant/raspberrypi2-homeassistant:0.107.1
    user: 1003:1003
    init: true
    network_mode: host
    volumes:
      - type: bind
        source: /home/homeassistant/config
        target: /config
    devices:
      - /dev/ttyUSB_P1
    environment:
      - TZ=Europe/Amsterdam
    restart: always
```

This is also mentioned in home-assistant/supervisor#1560, which references home-assistant/supervisor#1556. The latter issue seems to be related but the solution (running the installation script) is not applicable to Docker containers, so that will not work here.
