### ISSUE TITLE
[FATAL tini (6)] exec /bin/entry.sh failed: No such file or directory

### ISSUE THREAD

**Issue by sgofferj** [home-assistant/docker#107]
Just pulled the latest stable image: sha256:c836c31c0b797d5818ccd6fd8dd3ee512cf3526eeb95ca65f80a0193b20e9fb8 and it won't come up. Just seeing
[FATAL tini (6)] exec /bin/entry.sh failed: No such file or directory
repeating in the container output.

**Comment by frenck** [comment]
This is most likely caused by overriding the CMD in your docker settings.
One should not override that, unless you have a good reason to.

In this release our internal CMD has been replaced by a entry point that starts a init. So probably just removing the CMD from your settings will fix it.

**Comment by mazhead** [comment]
@frenck 
Have the same issue on the latest stable.
Using stock compose:

```
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - homeassistant:/config
    environment:
      - TZ=Europe/Prague
    restart: always
    network_mode: host

volumes:
  homeassistant:
```

In this commit the ENTRYPOINT has been removed: https://github.com/home-assistant/docker/commit/f0bef9e9cc1a6ef51b238a75fc0208c3393a2e0c#diff-de2dfe904ac98a74495473e67a0d0e2c

Even if you move to S6 overlay you need to have a ENTRYPOINT pointing to init:
https://github.com/just-containers/s6-overlay/wiki#usage
